# Generated by Django 5.0.7 on 2024-11-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=60)),
                ('product_description', models.TextField()),
                ('product_prize', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
