# Generated by Django 5.0.7 on 2024-12-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='username',
        ),
    ]
