# Generated by Django 5.0.7 on 2024-12-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_brand_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_feature_description',
            field=models.TextField(null=True),
        ),
    ]
