# Generated by Django 5.0.7 on 2024-12-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_product_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_dimensions',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_model_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
